const NAMES=[
{"id":"promptus","n":"Promptus","say":"PROMP-tus","cat":"Latin","mean":"Ready, at hand (→ prompt, incl. the AI sense)","promise":"Ready when asked","test":"Strong","collision":"Clean","pitch":"Promptus — the team that's ready the moment you ask.","risks":"May hear 'prompt us' — reads as AI-prompt tooling, which could date fast or box you into one feature.","dom":{"com":"taken","ai":"avail","handle":"avail"},"lineage":"Claude, Notion"},
{"id":"valor","n":"Valor","say":"VAL-or","cat":"Latin","mean":"Courage; same root as 'value' (valere)","promise":"\"Be strong and courageous\" (Josh 1:9)","test":"Strong","collision":"Several","pitch":"Valor — we build the AI workforce that runs your business.","risks":"Strong military/valor-ant associations (incl. the game Valorant); several existing companies named Valor.","dom":{"com":"taken","ai":"taken","handle":"taken"},"lineage":"Stripe, Palantir"},
{"id":"simplex","n":"Simplex","say":"SIM-plex","cat":"Latin","mean":"Simple, single, one-fold","promise":"One layer, not twelve","test":"Strong","collision":"Fire alarms","pitch":"Simplex — complex work, made one-fold.","risks":"Herpes simplex is the elephant in the room; also a fire-alarm brand and a math term (simplex algorithm).","dom":{"com":"taken","ai":"taken","handle":"taken"},"lineage":"Stripe, Slack"},
{"id":"forma","n":"Forma","say":"FOR-ma","cat":"Latin","mean":"Form, shape","promise":"Brings structure to ideas","test":"Good","collision":"Several","pitch":"Forma — we give shape to what your business could be.","risks":"Several small companies; 'forma' is a common word in skincare/fitness brands. Can feel abstract.","dom":{"com":"taken","ai":"taken","handle":"taken"},"lineage":"Notion, Figma"},
{"id":"utilis","n":"Utilis","say":"YOO-ti-lis","cat":"Latin","mean":"Useful (→ utility)","promise":"Plain usefulness","test":"Good","collision":"Minor","pitch":"Utilis — useful, and nothing but.","risks":"Sounds like 'utility' — reads as infrastructure, not a colleague. Hard to love; 'a Utilis shop' is awkward.","dom":{"com":"taken","ai":"avail","handle":"avail"},"lineage":"Stripe, Square"},
{"id":"beam","n":"Beam","say":"BEEM","cat":"English","mean":"A support beam; a beam of light","promise":"Holds things up and lights the way","test":"Strong","collision":"Beam Therapeutics","pitch":"Beam — the support under your business and the light ahead of it.","risks":"Beam Therapeutics is a well-funded biotech; also 'Beam' dental, Beam (crypto). Crowded but in other lanes.","dom":{"com":"taken","ai":"taken","handle":"taken"},"lineage":"Apple, Stripe"},
{"id":"harness","n":"Harness","say":"HAR-ness","cat":"English","mean":"Gear that puts power to work; \"harness AI\"","promise":"Makes AI pull for you","test":"Strong","collision":"Harness.io","pitch":"Harness — we put AI to work pulling for you.","risks":"Harness.io is a large dev-tools company in adjacent tech — real collision. Also literal gear connotation.","dom":{"com":"taken","ai":"taken","handle":"taken"},"lineage":"Stripe, Datadog"},
{"id":"aster","n":"Aster","say":"AS-ter","cat":"English","mean":"A flower; Greek aster = star","promise":"Growth meets the heavens","test":"Good","collision":"Several small","pitch":"Aster — growth, pointed at the stars.","risks":"Starts with 'ass-' in writing; may hear 'asterisk'. Several small collisions.","dom":{"com":"taken","ai":"taken","handle":"taken"},"lineage":"Notion, Anthropic"},
{"id":"oversight","n":"Oversight","say":"O-ver-site","cat":"English","mean":"Watching over everything; also the thing you missed","promise":"Supervision with a wink","test":"Weak","collision":"Generic","pitch":"Oversight — nothing slips past your business again.","risks":"Double meaning is the problem: an oversight is literally a mistake. 'We hired Oversight' invites the joke.","dom":{"com":"taken","ai":"taken","handle":"taken"},"lineage":"—"},
{"id":"starwell","n":"Starwell","say":"STAR-well","cat":"Coined","mean":"Guiding star + wellspring","promise":"Guidance and deep capability","test":"Good","collision":"Minor","pitch":"Starwell — guidance from above, depth from below.","risks":"Coined compound — needs explaining once. May hear 'Stairwell' or 'StarWell' pharma.","dom":{"com":"avail","ai":"avail","handle":"avail"},"lineage":"Verizon, Accenture"},
{"id":"optitude","n":"Optitude","say":"OP-ti-tood","cat":"Coined","mean":"Optimize + aptitude","promise":"Capability applied well","test":"Fair","collision":"Clean","pitch":"Optitude — the aptitude to optimize everything.","risks":"Blend reads as marketing-speak; '-itude' suffix feels dated (cf. 'turntitude'). May hear 'opti-tood'.","dom":{"com":"avail","ai":"avail","handle":"avail"},"lineage":"—"},
{"id":"servolution","n":"Servolution","say":"ser-vo-LOO-shun","cat":"Coined","mean":"Service + solution + evolution","promise":"Improving businesses through service","test":"Fair","collision":"Clean","pitch":"Servolution — service that evolves with you.","risks":"Four syllables, three blends — nobody will spell it from hearing it. Church movement already uses it.","dom":{"com":"taken","ai":"avail","handle":"taken"},"lineage":"—"}
];
const API_URL=window.API_URL||"";
